id: IAD1DEE32
legacy_id: P008196
ocr_import_info:
  bdrc_scan_id: W1CZ1395
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:44:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:03:25.328816+00:00'
last_modified: 2022-08-31 03:03:56.771207
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1395
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1395
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་འགྲེལ་པ་རྡོ་རྗེའི་རྣལ་འབྱོར་གྱི་དེ་ཁོ་ན་ཉིད་སྣང་བར་བྱེད་པའི་ཉི་མ་ཆེན་པོ།
  author: ཏཱ་ལའི་བླ་མ ༠༢་དགེ་འདུན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7578961659652778
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1CZ1620:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1620
      total_pages: 328
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1620.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.7578961659652778
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
