id: P008196
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1395
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་འགྲེལ་པ་རྡོ་རྗེའི་རྣལ་འབྱོར་གྱི་དེ་ཁོ་ན་ཉིད་སྣང་བར་བྱེད་པའི་ཉི་མ་ཆེན་པོ
  author: ''
  volumes:
    72a49991f5f64c7e9b1fcf9308aa230f:
      image_group_id: I1CZ1620
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
