id: P008196
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:07:22.408048
source_metadata:
  id: bdr:W1CZ1395
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་འགྲེལ་པ་རྡོ་རྗེའི་རྣལ་འབྱོར་གྱི་དེ་ཁོ་ན་ཉིད་སྣང་བར་བྱེད་པའི་ཉི་མ་ཆེན་པོ
  author: ''
  volumes:
    72a49991f5f64c7e9b1fcf9308aa230f:
      image_group_id: I1CZ1620
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
