id: P008196
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1395
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་འགྲེལ་པ་རྡོ་རྗེའི་རྣལ་འབྱོར་གྱི་དེ་ཁོ་ན་ཉིད་སྣང་བར་བྱེད་པའི་ཉི་མ་ཆེན་པོ
  author: ''
  volumes: {}
